config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  root to: 'base#index'
  resource :configuration
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/hierarchy.rb
class Hierarchy < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :configuration
  state_machine :initial => :unknown, :attribute => :state_value do
    event :apply_to_store do
      transition [:unknown,:repair,:site] => :store
    end
    event :apply_to_site do
      transition :store => :site
    end
    event :apply_to_recycle do
      transition [:store,:repair] => :recycle
    end
    event :apply_to_repair do
      transition :store => :repair
    end
  end
end

app/models/item_history.rb
class ItemHistory < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :rememberable, :trackable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in,keys: [:email])
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  def projects
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
  before_action :set_configuration, only: [:show, :edit, :update, :destroy]

  # GET /configurations
  # GET /configurations.json
  def index
    @configurations = Configuration.all
  end

  # GET /configurations/1
  # GET /configurations/1.json
  def show
  end

  # GET /configurations/new
  def new
    @configuration = Configuration.new
  end

  # GET /configurations/1/edit
  def edit
  end

  # POST /configurations
  # POST /configurations.json
  def create
    @configuration = Configuration.new(configuration_params)

    respond_to do |format|
      if @configuration.save
        format.html { redirect_to @configuration, notice: 'Configuration was successfully created.' }
        format.json { render :show, status: :created, location: @configuration }
      else
        format.html { render :new }
        format.json { render json: @configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configurations/1
  # PATCH/PUT /configurations/1.json
  def update
    respond_to do |format|
      if @configuration.update(configuration_params)
        format.html { redirect_to @configuration, notice: 'Configuration was successfully updated.' }
        format.json { render :show, status: :ok, location: @configuration }
      else
        format.html { render :edit }
        format.json { render json: @configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configurations/1
  # DELETE /configurations/1.json
  def destroy
    @configuration.destroy
    respond_to do |format|
      format.html { redirect_to configurations_url, notice: 'Configuration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuration
      @configuration = Configuration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def configuration_params
      params.fetch(:configuration, {})
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:projectname, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title_content
    content_for(:title) || ""
  end
  def lwi(path,text,icon)
  	link_to path do 
  		t = content_tag :i, nil, :class => icon
  		t+' '+text
  	end
  end

  def liwi(path,text,parms)
    link_to path do
      t = content_tag :i, nil, :class => parms
      t+' '+text
    end
  end

  def menu_helper

  	if user_signed_in?
  	end
  end

end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/base/index.html.erb
<% content_for :title do %>
<% "Home Page" %>
<% end %>
<h1 class="ui medium header">Добро Пожаловать!!!</h1>
<%= lwi(root_path, "Domoi!","home icon") %>

app/views/configurations/_form.html.erb
<%= form_for(@configuration) do |f| %>
  <% if @configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@configuration.errors.count, "error") %> prohibited this configuration from being saved:</h2>

      <ul>
      <% @configuration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/configurations/edit.html.erb
<h1>Editing Configuration</h1>

<%= render 'form', configuration: @configuration %>

<%= link_to 'Show', @configuration %> |
<%= link_to 'Back', configurations_path %>

app/views/configurations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Configurations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configurations.each do |configuration| %>
      <tr>
        <td><%= link_to 'Show', configuration %></td>
        <td><%= link_to 'Edit', edit_configuration_path(configuration) %></td>
        <td><%= link_to 'Destroy', configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Configuration', new_configuration_path %>

app/views/configurations/new.html.erb
<h1>New Configuration</h1>

<%= render 'form', configuration: @configuration %>

<%= link_to 'Back', configurations_path %>

app/views/configurations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_configuration_path(@configuration) %> |
<%= link_to 'Back', configurations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= title_content %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style type="text/css">
    .ui.menu .item img.logo {
      margin-right: 1.5em;
    }
  </style>
</head>
<body>

  <% if user_signed_in? %>
      <%= render 'utils/nav_bar_signed' %>
  <% else %>
      <%= render 'utils/nav_bar_unsigned' %>
  <% end %>

<div class="ui container">

  <%= yield %>

</div>



</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project, html: { class: "ui form"}) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :projectname %>
    <%= f.text_field :projectname %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div>
    <%= f.submit :class => "ui button" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список проектов</h1>

<table class="ui table">
  <thead>
    <tr>
      <th colspan=3>
      <%= link_to 'Добавить проект', new_project_path, :class => "ui button small black" %>
      </th>
    </tr>
    <tr>
      <th>Наименование проекта</th>
      <th>Комментарии</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.projectname %></td>
        <td><%= project.comment %></td>
        <td>
          <div class="ui buttons small">
            <%= link_to 'Просмотр', project, :class => "ui button green" %>
            <%= link_to 'Правка', edit_project_path(project), :class => "ui button blue" %>
            <%= link_to 'Удалить', project, method: :delete, data: { confirm: 'Вы уверены?' }, :class =>"ui button red" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projectname:</strong>
  <%= @project.projectname %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @project.comment %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/utils/_footer.erb
<div class="ui  inverted vertical footer segment">
  <div class="ui fixed center aligned container">
    <div class="ui stackable inverted divided grid">
      <div class="ui horizontal inverted mini  link list">
        <a class="item" href="#">Site Map</a>
        <a class="item" href="#">Contact Us</a>
        <a class="item" href="#">Terms and Conditions</a>
        <a class="item" href="#">Privacy Policy</a>
      </div>
    </div>
  </div>
</div>

app/views/utils/_nav_bar_signed.html.erb
<div class="ui inverted menu">
  <div class="ui container">
    <a href="#" class="header item">
      <%= image_tag "logo.png"%>
      &nbsp;&nbsp;Project Name
    </a>
    <div class="ui simple dropdown item">
      Справочники: <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item" href="#">Link Item</a>
        <a class="item" href="#">Link Item</a>
        <div class="divider"></div>
        <div class="header">Header Item</div>
        <div class="item">
          <i class="dropdown icon"></i>
          Sub Menu
          <div class="menu">
            <a class="item" href="#">Link Item</a>
            <a class="item" href="#">Link Item</a>
          </div>
        </div>
        <a class="item" href="#">Link Item</a>
      </div>
    </div>
  </div>
  <div class="header item">
    <%= link_to "Выход", destroy_user_session_path, :method  => :delete, :class => "ui item" %>
  </div>
</div>

app/views/utils/_nav_bar_unsigned.html.erb
<div class="ui inverted menu">
  <div class="ui container">
    <a href="#" class="header item center">
      <%= image_tag "logo.png", :size =>"27x29" %>
      Welcome to Project Name
    </a>
  </div>
</div>